blank_issues_enabled: false
contact_links:
  - name: Atlas GitHub Discussions
    url: https://github.com/AnoopNadagouda/Atlas/discussions
    about: Ask questions and interact with the open-source community.
